name: Testing 

on:
	push:
		branches: [master, develop]
	pull_request:
		branches: [master, develop]

jobs:
	build:
		runs-on: ubuntu-latest
		steps:
			- uses: actions/checkout@v2
			- uses: actions/setup-node@v4
			with:
				node-version: 20
			- run: npm ci
			- run: npm run test
			- run: npm run build
